name: Assets Check
on:
  push:
    branches:
      - "main"
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |-
          npx ts-node scripts/assets-check.ts
